version: '3.8'

services:
  server:
    restart: 'unless-stopped'
    ports:
      - $API_PORT:$API_PORT
    build:
      dockerfile: server.Dockerfile
      context: .
      args:
        API_PORT: $API_PORT
        APP_DIR: $APP_DIR
    volumes:
      - server_lein_cache:/root/.m2

  repl:
    restart: 'unless-stopped'
    ports:
      - $API_PORT:$API_PORT
      - $REPL_PORT:$REPL_PORT
    build:
      dockerfile: repl.Dockerfile
      context: .
      args:
        REPL_PORT: $REPL_PORT
        APP_DIR: $APP_DIR
    volumes:
      - .:$APP_DIR
      - repl_lein_cache:/root/.m2

volumes:
  repl_lein_cache:
  server_lein_cache:
