name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/aspenjames/clojure-api
  TEST_TAG: ${IMAGE_NAME}:test
  RELEASE_TAG: ${IMAGE_NAME}:latest

jobs:
  build:
    name: 🛠 Build and push to GitHub registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1.6.0

    - name: Setup Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${IMAGE_NAME}
        tags: |
          type=sha,prefix={{branch}}-

    - name: Build
      uses: docker/build-push-action@v2.10.0
      with:
        load: true
        file: server.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=local,src=/tmp/.docker-cache
        cache-to: type=local,src=/tmp/.docker-cache-new

    - name: Run tests
      run: |
        docker run --rm ${IMAGE_NAME}:${ GITHUB_SHA } 'lein test'

    - name: Push
      uses: docker/build-push-action@v2.10.0
      with:
        push: true
        file: server.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=local,src=/tmp/.docker-cache-new
        cache-to: type=local,src=/tmp/.docker-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
